site_name: HomeLab Documentation
site_url: https://lab.packetflow.be
theme: 
  name: material
  language: en
  features:
    # - toc.integrate # integrate toc into main navigation (left side)
    - navigation.path # Breadcrumbs
    - navigation.tabs # Show tabs on top of page
    - navigation.tabs.sticky # Tabs stay visible when scrolling
    - navigation.top # Show back-to-top button
    - content.code.copy
    - content.code.select
    - content.code.annotate
plugins:
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: long
      post_url_date_format: yyyy/MM
      post_url_format: "{date}/{categories}/{slug}"
  - search
  - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/declercklouis
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/declercklouis
    - icon: fontawesome/solid/globe
      link: https://packetflow.be
    - icon: fontawesome/solid/envelope
      link: mailto:louis@packetflow.be

copyright: Copyright &copy; 2026 Louis Declerck

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - Documentation:
    - Network:
      - Physical Layout: homelab/01_network/01_physical.md
      - Logical Layout: homelab/01_network/02_logical.md
      - Device Decisions: homelab/01_network/03_device_decisions.md
      - Security: homelab/01_network/04_security.md
      - Wireless: homelab/01_network/06_wireless.md
    - Systems:
      - Physical Layout: homelab/02_systems/01_physical.md
  - Status : status.md